name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.11

      # Cache bun dependencies
      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      # Add testing step when tests are implemented
      # - name: Test
      #   run: bun test

      - name: Create example site
        run: |
          mkdir -p test-site
          cd test-site
          ../dist/cli.js init
          ../dist/cli.js generate

      - name: Verify site generation
        run: |
          cd test-site
          if [ ! -f "dist/index.html" ]; then
            echo "Site generation failed"
            exit 1
          fi