name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.0

      # Cache bun dependencies
      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Verify TypeScript compilation
      - name: TypeScript check
        run: bun run typecheck

      # Verify code formatting
      - name: Check formatting
        run: bun run format:check

      # Run tests with coverage
      - name: Run tests with coverage
        run: bun test:coverage

      # Build the project
      - name: Build
        run: bun run build

      # Create and test example site
      - name: Create example site
        run: |
          mkdir -p test-site
          cd test-site
          ../dist/cli.js init
          ../dist/cli.js generate

      # Verify site generation succeeded
      - name: Verify site generation
        run: |
          cd test-site
          if [ ! -f "dist/index.html" ]; then
            echo "Site generation failed"
            exit 1
          fi

      # Check for basic site structure
      - name: Verify site structure
        run: |
          cd test-site
          # Check for critical files
          for file in dist/index.html dist/css/style.css dist/tags/index.html; do
            if [ ! -f "$file" ]; then
              echo "Missing expected file: $file"
              exit 1
            fi
          done
          echo "Site structure verification passed"
